---
language: python

# This (sudo: false) is needed to "run on container-based infrastructure" on
# which cache: is available
# https://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# https://docs.travis-ci.com/user/caching/
cache: pip

env:
  - SPHINXOPTS="-W"

script:
  - make clean html linkcheck
